# Generated by Django 5.2.17 on 2026-09-27 10:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(help_text='An emoji.', max_length=8)),
                ('category', models.CharField(choices=[('tracking', 'Tracking'), ('saving', 'Saving'), ('budgeting', 'Budgeting')], max_length=20)),
                ('rule', models.CharField(choices=[('first_transaction', 'First transaction recorded'), ('tracking_streak', 'Transactions recorded on consecutive days'), ('savings_total', 'Money saved in savings goals'), ('budget_kept', 'A finished month ended within a budget'), ('goal_completed', 'A savings goal reached its target')], max_length=30)),
                ('unit', models.CharField(choices=[('count', 'Count'), ('days', 'Days'), ('money', 'Money')], max_length=10)),
                ('target', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('target_currency', models.CharField(blank=True, choices=[('EUR', 'Euro'), ('HUF', 'Hungarian forint'), ('USD', 'US dollar'), ('GBP', 'British pound'), ('JPY', 'Japanese yen'), ('CHF', 'Swiss franc')], max_length=3, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('target__gt', 0)), name='achievement_target_positive'), models.CheckConstraint(condition=models.Q(models.Q(('target_currency__isnull', False), ('unit', 'money')), models.Q(models.Q(('unit', 'money'), _negated=True), ('target_currency__isnull', True)), _connector='OR'), name='achievement_currency_only_for_money')],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_achievements', to='analytics.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['achievement__sort_order', 'achievement_id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'achievement'), name='unique_user_achievement'), models.CheckConstraint(condition=models.Q(('progress__gte', 0)), name='user_achievement_progress_not_negative')],
            },
        ),
    ]
