# Generated by Django 5.2.17 on 2026-10-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_assistant_conversations'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmessage',
            name='insights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assistantmessage',
            name='suggested_questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
