# Generated by Django 5.2.17 on 2026-09-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('HUF', 'Hungarian forint'), ('USD', 'US dollar'), ('GBP', 'British pound'), ('JPY', 'Japanese yen'), ('CHF', 'Swiss franc')], max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'currency'],
                'constraints': [models.UniqueConstraint(fields=('currency', 'date'), name='exchange_rate_unique_currency_date'), models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='exchange_rate_positive'), models.CheckConstraint(condition=models.Q(('currency', 'EUR'), _negated=True), name='exchange_rate_not_eur')],
            },
        ),
    ]
