export interface TopSpendingCategory {
  category_id: number;
  category_name: string;
  amount: string;
}

/** over_budget: above the limit; ahead_of_pace: above what the elapsed part of the month allows. */
export type BudgetStatus = "on_track" | "ahead_of_pace" | "over_budget";

export interface BudgetUsageEntry {
  budget_id: number;
  category_id: number | null;
  category_name: string;
  budget_amount: string;
  spent_amount: string;
  remaining_amount: string;
  usage_percentage: number;
  /** Budget variance: above (+) or below (−) the limit, in % of the limit. */
  variance_percentage: number;
  /** What the budget allows by today, spread evenly over the month. */
  expected_to_date: string;
  status: BudgetStatus;
}

/**
 * Shape of GET /api/analytics/dashboard/. Every figure here — totals,
 * balance, top category, budget usage — is computed by the backend from
 * the user's transactions/budgets for the given month. Render it as-is;
 * don't derive or override any of these numbers on the client.
 */
export interface DashboardStats {
  year: number;
  month: number;
  total_income: string;
  total_expenses: string;
  balance: string;
  transaction_count: number;
  top_spending_category: TopSpendingCategory | null;
  budget_usage: BudgetUsageEntry[];
}

/** Query params accepted by GET /api/analytics/dashboard/ — both default to the current month. */
export interface DashboardParams {
  year?: number;
  month?: number;
}

export interface MonthlyDataPoint {
  month: number;
  month_name: string;
  income: string;
  expenses: string;
  balance: string;
}

/** Shape of GET /api/analytics/monthly/ — always 12 entries, zero-filled for months with no data. */
export interface MonthlyAnalytics {
  year: number;
  months: MonthlyDataPoint[];
}

export interface MonthlyAnalyticsParams {
  year?: number;
}

export interface CategoryBreakdownEntry {
  category_id: number;
  category_name: string;
  amount: string;
  /** Share of that month's total expenses, 0-100. */
  percentage: number;
}

/** Shape of GET /api/analytics/categories/ — expense categories only, sorted by amount descending. */
export interface CategoryAnalytics {
  year: number;
  month: number;
  categories: CategoryBreakdownEntry[];
}

export interface CategoryAnalyticsParams {
  year?: number;
  month?: number;
}

export type InsightSeverity = "alert" | "warning" | "positive" | "info";

export type InsightType =
  | "top_category"
  | "category_increase"
  | "category_decrease"
  | "budget_exceeded"
  | "budget_warning"
  | "recurring_share"
  | "overspending"
  | "savings";

/**
 * One rule-based insight, fully generated by the backend — the message text,
 * amount and percentage are ready to display as-is.
 */
export interface Insight {
  /** Stable key, e.g. "budget_exceeded:12". */
  id: string;
  type: InsightType;
  severity: InsightSeverity;
  message: string;
  category_id: number | null;
  /** Decimal string; its meaning depends on `type` (see docs/api-contract.md). */
  amount: string | null;
  percentage: number | null;
}

/** Shape of GET /api/analytics/insights/ — sorted by severity: alert, warning, positive, info. */
export interface InsightsResponse {
  year: number;
  month: number;
  insights: Insight[];
}

export interface InsightsParams {
  year?: number;
  month?: number;
}

// --- Trends, comparisons, merchants, spending patterns -------------------------------------
// Every amount is a decimal string in the user's base currency, computed by the backend.

export interface MonthSummary {
  year: number;
  month: number;
  total_income: string;
  total_expenses: string;
  balance: string;
  transaction_count: number;
}

export type ComparisonAgainst = "previous_month" | "previous_year";

export interface CategoryComparison {
  category_id: number;
  category_name: string;
  current_amount: string;
  previous_amount: string;
  change_amount: string;
  /** null when nothing was spent in the compared month. */
  change_percentage: number | null;
}

/** Shape of GET /api/analytics/comparison/ — `previous_month` is the month compared against. */
export interface Comparison {
  against: ComparisonAgainst;
  current_month: MonthSummary;
  previous_month: MonthSummary;
  difference: { total_income: string; total_expenses: string; balance: string };
  percentage_difference: { total_income: number | null; total_expenses: number | null; balance: number | null };
  categories: CategoryComparison[];
}

export interface ComparisonParams {
  year?: number;
  month?: number;
  against?: ComparisonAgainst;
}

export interface TrendMonth {
  year: number;
  month: number;
  month_name: string;
  income: string;
  expenses: string;
  balance: string;
  expenses_change_percentage: number | null;
}

export interface CategoryTrend {
  category_id: number;
  category_name: string;
  /** One amount per entry of `Trends.months`, same order. */
  amounts: string[];
  total: string;
  average: string;
  /** The latest month minus the month before it. */
  change_amount: string;
  change_percentage: number | null;
}

/** Shape of GET /api/analytics/trends/ — the last `months` months, oldest first. */
export interface Trends {
  year: number;
  month: number;
  months: TrendMonth[];
  average_monthly_expenses: string;
  categories: CategoryTrend[];
}

export interface TrendsParams {
  year?: number;
  month?: number;
  /** 2–24, default 6. */
  months?: number;
}

export interface Merchant {
  merchant: string;
  transaction_count: number;
  total: string;
  average: string;
  share_percentage: number | null;
  previous_total: string;
  change_percentage: number | null;
  last_date: string;
}

/** Shape of GET /api/analytics/merchants/ — largest first. */
export interface Merchants {
  year: number;
  month: number;
  total_expenses: string;
  merchants: Merchant[];
}

export interface MerchantsParams {
  year?: number;
  month?: number;
  /** 1–50, default 10. */
  limit?: number;
}

export interface WeekdaySpending {
  /** ISO weekday: 1 = Monday … 7 = Sunday. */
  weekday: number;
  name: string;
  total: string;
  transaction_count: number;
  days: number;
  average_per_day: string | null;
}

/** Shape of GET /api/analytics/spending-patterns/ — month-to-date for the current month. */
export interface SpendingPatterns {
  year: number;
  month: number;
  days_counted: number;
  total_expenses: string;
  average_daily_spending: string | null;
  weekdays: WeekdaySpending[];
  fixed_expenses: string;
  variable_expenses: string;
  fixed_percentage: number | null;
  recurring_commitments: string;
}
