# Generated by Django 5.2.17 on 2026-09-27 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def carry_over_existing_state(apps, schema_editor):
    NotificationPreference = apps.get_model("notifications", "NotificationPreference")
    Notification = apps.get_model("notifications", "Notification")
    # Subscription reminders used to be part of the recurring reminders: keep the user's choice.
    NotificationPreference.objects.update(subscription_reminders=models.F("recurring_reminders"))
    # Notifications from before the in-app inbox were push-only; don't greet users with a pile of "unread".
    Notification.objects.filter(read_at__isnull=True).update(read_at=models.F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='monthly_summary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='savings_goals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='subscription_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='unusual_spending',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('budget_warning', 'Budget almost used'), ('budget_exceeded', 'Budget exceeded'), ('subscription_due', 'Subscription payment approaching'), ('recurring_due', 'Upcoming recurring expense'), ('savings_goal', 'Savings goal progress'), ('unusual_spending', 'Unusual spending'), ('monthly_summary', 'Monthly spending summary'), ('insight', 'Important insight')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notification_inbox_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(condition=models.Q(('read_at__isnull', True)), fields=['user'], name='notification_unread_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['content_type', 'object_id'], name='notification_related_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('content_type__isnull', True), ('object_id__isnull', True)), models.Q(('content_type__isnull', False), ('object_id__isnull', False)), _connector='OR'), name='notification_related_complete'),
        ),
        migrations.RunPython(carry_over_existing_state, migrations.RunPython.noop),
    ]
