# Generated by Django 5.2.17 on 2026-09-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_email_case_insensitive_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='base_currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('HUF', 'Hungarian forint'), ('USD', 'US dollar'), ('GBP', 'British pound'), ('JPY', 'Japanese yen'), ('CHF', 'Swiss franc')], default='EUR', max_length=3),
        ),
    ]
