# Generated by Django 5.2.17 on 2026-09-28 15:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_base_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotpDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_secret', models.TextField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_step', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_device', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('account_created', 'Account created'), ('login_succeeded', 'Signed in'), ('login_failed', 'Wrong email or password'), ('login_blocked', 'Sign-in blocked after too many failures'), ('mfa_failed', 'Wrong two-factor code'), ('logout', 'Signed out'), ('logout_all', 'Signed out everywhere'), ('session_revoked', 'Device signed out'), ('refresh_token_reused', 'Stolen session blocked'), ('password_changed', 'Password changed'), ('mfa_enabled', 'Two-factor authentication turned on'), ('mfa_disabled', 'Two-factor authentication turned off'), ('recovery_code_used', 'Recovery code used'), ('recovery_codes_regenerated', 'New recovery codes'), ('base_currency_changed', 'Base currency changed'), ('transactions_imported', 'Transactions imported'), ('object_deleted', 'Deleted')], max_length=30)),
                ('email', models.CharField(blank=True, default='', max_length=254)),
                ('session_key', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='audit_user_created_idx'), models.Index(fields=['email', 'action', 'created_at'], name='audit_login_attempts_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'code_hash'], name='recovery_code_lookup_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('platform', models.CharField(choices=[('web', 'Web'), ('ios', 'iOS'), ('android', 'Android'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('refresh_jti', models.CharField(max_length=64)),
                ('previous_refresh_jti', models.CharField(blank=True, default='', max_length=64)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, choices=[('logout', 'Logged out'), ('logout_all', 'Logged out everywhere'), ('revoked', 'Signed out from another device'), ('password_changed', 'Password changed'), ('token_reuse', 'Refresh token reused (possible theft)'), ('expired', 'Session too old')], default='', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used_at', '-id'],
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='session_user_active_idx')],
            },
        ),
    ]
