# Generated by Django 5.2.17 on 2026-10-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_account_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hu', 'Magyar')], default='en', max_length=8),
        ),
    ]
