# Generated by Django 5.2.17 on 2026-10-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('account_created', 'Account created'), ('login_succeeded', 'Signed in'), ('login_failed', 'Wrong email or password'), ('login_blocked', 'Sign-in blocked after too many failures'), ('mfa_failed', 'Wrong two-factor code'), ('logout', 'Signed out'), ('logout_all', 'Signed out everywhere'), ('session_revoked', 'Device signed out'), ('refresh_token_reused', 'Stolen session blocked'), ('password_changed', 'Password changed'), ('mfa_enabled', 'Two-factor authentication turned on'), ('mfa_disabled', 'Two-factor authentication turned off'), ('recovery_code_used', 'Recovery code used'), ('recovery_codes_regenerated', 'New recovery codes'), ('base_currency_changed', 'Base currency changed'), ('transactions_imported', 'Transactions imported'), ('object_deleted', 'Deleted'), ('data_exported', 'Personal data downloaded')], max_length=30),
        ),
    ]
