# Generated by Django 5.2.17 on 2026-09-26 13:43

import django.db.models.expressions
import django.db.models.functions.math
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_is_system'),
        ('transactions', '0003_category_restrict'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, default=Decimal('1'), max_digits=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('HUF', 'Hungarian forint'), ('USD', 'US dollar'), ('GBP', 'British pound'), ('JPY', 'Japanese yen'), ('CHF', 'Swiss franc')], default='EUR', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='transaction_exchange_rate_positive'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='base_amount',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.math.Round(django.db.models.expressions.CombinedExpression(models.F('amount'), '*', models.F('exchange_rate')), 2), output_field=models.DecimalField(decimal_places=2, max_digits=15)),
        ),
    ]
