# Generated by Django 5.2.17 on 2026-09-27 09:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('HUF', 'Hungarian forint'), ('USD', 'US dollar'), ('GBP', 'British pound'), ('JPY', 'Japanese yen'), ('CHF', 'Swiss franc')], default='EUR', max_length=3)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_date', 'name', 'id'],
                'indexes': [models.Index(fields=['user', 'status'], name='savings_goal_user_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('target_amount__gt', 0)), name='savings_goal_target_positive'), models.CheckConstraint(condition=models.Q(('current_amount__gte', 0)), name='savings_goal_current_not_negative')],
            },
        ),
    ]
