from decimal import Decimal

from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models.functions import Round

from apps.categories.models import Category, TransactionType
from apps.currencies.models import Currency


class Transaction(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="transactions"
    )
    # RESTRICT, not PROTECT: a category in use can't be deleted on its own, but deleting
    # the user (which removes their categories *and* transactions together) still works.
    category = models.ForeignKey(Category, on_delete=models.RESTRICT, related_name="transactions")
    recurring_transaction = models.ForeignKey(
        "RecurringTransaction",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="generated_transactions",
    )
    type = models.CharField(max_length=10, choices=TransactionType.choices)
    # The amount as it was paid, in `currency` — never rewritten.
    amount = models.DecimalField(
        max_digits=12, decimal_places=2, validators=[MinValueValidator(Decimal("0.01"))]
    )
    # Default EUR: every transaction recorded before multi-currency support was in euros.
    currency = models.CharField(max_length=3, choices=Currency.choices, default=Currency.EUR)
    # Value of 1 unit of `currency` in the user's base currency (1 when they are the same).
    # Fixed when the transaction is saved; see apps/currencies/rates.py.
    exchange_rate = models.DecimalField(max_digits=20, decimal_places=10, default=Decimal(1))
    # `amount` in the user's base currency. Computed by the database, so it can never
    # disagree with amount × exchange_rate. Every total (analytics, budgets) sums this.
    base_amount = models.GeneratedField(
        expression=Round(models.F("amount") * models.F("exchange_rate"), 2),
        output_field=models.DecimalField(max_digits=15, decimal_places=2),
        db_persist=True,
    )
    description = models.CharField(max_length=255, blank=True, default="")
    date = models.DateField()
    # Idempotency key generated by the mobile app for transactions recorded
    # offline: re-sending the same client_id returns the existing row instead
    # of creating a duplicate. Null for transactions created online / on web.
    client_id = models.UUIDField(null=True, blank=True, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-date", "-created_at"]
        constraints = [
            models.CheckConstraint(condition=models.Q(amount__gt=0), name="transaction_amount_positive"),
            models.CheckConstraint(
                condition=models.Q(exchange_rate__gt=0), name="transaction_exchange_rate_positive"
            ),
            models.UniqueConstraint(
                fields=["user", "client_id"],
                condition=models.Q(client_id__isnull=False),
                name="transaction_unique_client_id",
            ),
        ]
        indexes = [
            models.Index(fields=["user", "date"], name="transaction_user_date_idx"),
            models.Index(fields=["user", "type"], name="transaction_user_type_idx"),
        ]

    def clean(self):
        if self.category_id and self.type and self.category.type != self.type:
            raise ValidationError(
                {"type": "Transaction type must match the selected category's type."}
            )

    def __str__(self):
        return f"{self.date} · {self.get_type_display()} · {self.amount} {self.currency}"


class Frequency(models.TextChoices):
    WEEKLY = "weekly", "Weekly"
    MONTHLY = "monthly", "Monthly"
    YEARLY = "yearly", "Yearly"


class RecurringTransaction(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="recurring_transactions"
    )
    category = models.ForeignKey(
        Category, on_delete=models.RESTRICT, related_name="recurring_transactions"
    )
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=10, choices=TransactionType.choices)
    # The amount of one occurrence as billed, in `currency` — never rewritten (a Netflix
    # plan billed in USD stays 15.49 USD). Totals convert it to the base currency.
    amount = models.DecimalField(
        max_digits=12, decimal_places=2, validators=[MinValueValidator(Decimal("0.01"))]
    )
    currency = models.CharField(max_length=3, choices=Currency.choices, default=Currency.EUR)
    # Who gets paid (landlord, "Netflix Inc.", employer). Optional; `name` is the label.
    merchant = models.CharField(max_length=100, blank=True, default="")
    # Subscriptions (streaming, software, gym, phone, …) are recurring expenses managed
    # through /api/subscriptions/ — see apps/subscriptions. Same row, same table.
    is_subscription = models.BooleanField(default=False)
    frequency = models.CharField(max_length=10, choices=Frequency.choices)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    next_occurrence_date = models.DateField()
    is_active = models.BooleanField(default=True)
    description = models.CharField(max_length=255, blank=True, default="")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["next_occurrence_date"]
        constraints = [
            models.CheckConstraint(condition=models.Q(amount__gt=0), name="recurring_amount_positive"),
            models.CheckConstraint(
                condition=models.Q(end_date__isnull=True) | models.Q(end_date__gte=models.F("start_date")),
                name="recurring_end_date_after_start_date",
            ),
            models.CheckConstraint(
                condition=models.Q(is_subscription=False) | models.Q(type=TransactionType.EXPENSE),
                name="recurring_subscription_is_expense",
            ),
        ]
        indexes = [
            models.Index(fields=["user", "is_active"], name="recurring_user_active_idx"),
            models.Index(fields=["user", "next_occurrence_date"], name="recurring_user_next_occ_idx"),
        ]

    def clean(self):
        if self.category_id and self.type and self.category.type != self.type:
            raise ValidationError(
                {"type": "Recurring transaction type must match the selected category's type."}
            )
        if self.is_subscription and self.type != TransactionType.EXPENSE:
            raise ValidationError({"type": "Subscriptions are always expenses."})

    def __str__(self):
        return f"{self.name} ({self.get_frequency_display()})"
